pipeline {
    agent any
    parameters {
      string defaultValue: '', description: 'Build/Tag name of the image to create a container', name: 'BUILD_NAME', trim: false
      string defaultValue: '', description: 'Build/Tag of previous image to stop/delete containers', name: 'LAST_BUILD_NAME', trim: false
    }
    stages {
        stage('deploy') {
            steps {
                echo params.BUILD_NAME
                echo params.LAST_BUILD_NAME
                bat "docker rm -f node_uady_sicei"
                bat "docker container run -d -e DB_HOST=host.docker.internal -e DB_PORT=3306 -e DB_USERNAME=root -e DB_PASSWORD=pa\$\$word1 -e DB_NAME=uady_sicei -p 8081:8080 --name node_uady_sicei "+params.BUILD_NAME
                bat "docker rm -f "+ params.LAST_BUILD_NAME + " || echo 'removing old image failed but shouldn't stop'"
            }
        }
    }
    post {
        success {
            echo "Deploy success"
            echo params.BUILD_NAME
            echo params.LAST_BUILD_NAME
            //call other job
        }
    }
}